// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef edit_h
#define edit_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Input.H>
extern Fl_Input *dt;
extern Fl_Input *tx;
extern Fl_Input *ty;
extern Fl_Input *tz;
extern Fl_Input *rx;
extern Fl_Input *ry;
extern Fl_Input *rz;
#endif
