// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RunAccess - Use 'RunAccessParams' to pass parameters into this method.
        /// </summary>
        public void RunAccess()
        {
            #region Variable Declarations
            WinCustom uIItemCustom = this.UIMicrosoftAccessPreviWindow.UIItemCustom;
            WinCustom uIItemCustom1 = this.UIMicrosoftAccessPreviWindow.UIItemCustom1;
            WinCustom uIItemCustom2 = this.UIMicrosoftAccessPreviWindow.UIItemCustom2;
            WinClient uIItemClient = this.UIMicrosoftAccessPreviWindow.UIItemWindow.UIItemClient;
            WinCustom uIItemCustom3 = this.UISaveAsWindow.UIItemCustom;
            WinCustom uIItemCustom31 = this.UIMicrosoftAccessPreviWindow.UIItemCustom3;
            #endregion

            // Launch '%ProgramW6432%\Microsoft Office 15\root\office15\msaccess.exe' with arguments '""'
            ApplicationUnderTest msaccessApplication = ApplicationUnderTest.Launch(this.RunAccessParams.ExePath, this.RunAccessParams.AlternateExePath, "\"\"");

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(772, 335));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(772, 335));

            // Type 'Something{Enter}' in custom control
            Keyboard.SendKeys(uIItemCustom1, this.RunAccessParams.UIItemCustom1SendKeys, ModifierKeys.None);

            // Click custom control
            Mouse.Click(uIItemCustom2, new Point(432, 283));

            // Type 'My{Space}Name{Space}is{Space}Jonas{Tab}' in client
            Keyboard.SendKeys(uIItemClient, this.RunAccessParams.UIItemClientSendKeys, ModifierKeys.None);

            // Type 'Control + s' in client
            Keyboard.SendKeys(uIItemClient, this.RunAccessParams.UIItemClientSendKeys1, ModifierKeys.Control);

            // Type 'M{Back}Joh{Back}{Back}onas{Enter}' in custom control
            Keyboard.SendKeys(uIItemCustom3, this.RunAccessParams.UIItemCustomSendKeys, ModifierKeys.None);

            // The control for this action was not recorded.

            // The control for this action was not recorded.

            // The control for this action was not recorded.

            // Click custom control
            Mouse.Click(uIItemCustom31, new Point(1500, 93));
        }
        
        /// <summary>
        /// StartAccess - Use 'StartAccessParams' to pass parameters into this method.
        /// </summary>
        public void StartAccess()
        {

            // Launch '%ProgramW6432%\Microsoft Office 15\ClientX64\integratedoffice.exe' with arguments 'LAUNCH app "root\Office15\MSACCESS.EXE" apparg ""'
            ApplicationUnderTest integratedofficeApplication = ApplicationUnderTest.Launch(this.StartAccessParams.ExePath, this.StartAccessParams.AlternateExePath, "LAUNCH app \"root\\Office15\\MSACCESS.EXE\" apparg \"\"");
        }
        
        #region Properties
        public virtual RunAccessParams RunAccessParams
        {
            get
            {
                if ((this.mRunAccessParams == null))
                {
                    this.mRunAccessParams = new RunAccessParams();
                }
                return this.mRunAccessParams;
            }
        }
        
        public virtual StartAccessParams StartAccessParams
        {
            get
            {
                if ((this.mStartAccessParams == null))
                {
                    this.mStartAccessParams = new StartAccessParams();
                }
                return this.mStartAccessParams;
            }
        }
        
        public UIMicrosoftAccessPreviWindow UIMicrosoftAccessPreviWindow
        {
            get
            {
                if ((this.mUIMicrosoftAccessPreviWindow == null))
                {
                    this.mUIMicrosoftAccessPreviWindow = new UIMicrosoftAccessPreviWindow();
                }
                return this.mUIMicrosoftAccessPreviWindow;
            }
        }
        
        public UISaveAsWindow UISaveAsWindow
        {
            get
            {
                if ((this.mUISaveAsWindow == null))
                {
                    this.mUISaveAsWindow = new UISaveAsWindow();
                }
                return this.mUISaveAsWindow;
            }
        }
        #endregion
        
        #region Fields
        private RunAccessParams mRunAccessParams;
        
        private StartAccessParams mStartAccessParams;
        
        private UIMicrosoftAccessPreviWindow mUIMicrosoftAccessPreviWindow;
        
        private UISaveAsWindow mUISaveAsWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RunAccess'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RunAccessParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office 15\root\office15\msaccess.exe' with arguments '""'
        /// </summary>
        public string ExePath = "C:\\Program Files\\Microsoft Office 15\\root\\office15\\msaccess.exe";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office 15\root\office15\msaccess.exe' with arguments '""'
        /// </summary>
        public string AlternateExePath = "%ProgramW6432%\\Microsoft Office 15\\root\\office15\\msaccess.exe";
        
        /// <summary>
        /// Type 'Something{Enter}' in custom control
        /// </summary>
        public string UIItemCustom1SendKeys = "Something{Enter}";
        
        /// <summary>
        /// Type 'My{Space}Name{Space}is{Space}Jonas{Tab}' in client
        /// </summary>
        public string UIItemClientSendKeys = "My{Space}Name{Space}is{Space}Jonas{Tab}";
        
        /// <summary>
        /// Type 'Control + s' in client
        /// </summary>
        public string UIItemClientSendKeys1 = "s";
        
        /// <summary>
        /// Type 'M{Back}Joh{Back}{Back}onas{Enter}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys = "M{Back}Joh{Back}{Back}onas{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StartAccess'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class StartAccessParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office 15\ClientX64\integratedoffice.exe' with arguments 'LAUNCH app "root\Office15\MSACCESS.EXE" apparg ""'
        /// </summary>
        public string ExePath = "C:\\Program Files\\Microsoft Office 15\\ClientX64\\integratedoffice.exe";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Microsoft Office 15\ClientX64\integratedoffice.exe' with arguments 'LAUNCH app "root\Office15\MSACCESS.EXE" apparg ""'
        /// </summary>
        public string AlternateExePath = "%ProgramW6432%\\Microsoft Office 15\\ClientX64\\integratedoffice.exe";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMicrosoftAccessPreviWindow : WinWindow
    {
        
        public UIMicrosoftAccessPreviWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Microsoft Access Preview";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "OMain";
            this.WindowTitles.Add("Microsoft Access Preview");
            this.WindowTitles.Add("Microsoft Access Preview - Something : Database- C:\\Users\\andrewjo\\Documents\\Some" +
                    "thing.accdb (Access 2007 - 2013 file format)");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Microsoft Access Preview");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.WindowTitles.Add("Microsoft Access Preview");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        
        public WinCustom UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom2.WindowTitles.Add("Microsoft Access Preview - Something : Database- C:\\Users\\andrewjo\\Documents\\Some" +
                            "thing.accdb (Access 2007 - 2013 file format)");
                    #endregion
                }
                return this.mUIItemCustom2;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public WinCustom UIItemCustom3
        {
            get
            {
                if ((this.mUIItemCustom3 == null))
                {
                    this.mUIItemCustom3 = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom3.WindowTitles.Add("Microsoft Access Preview - Something : Database- C:\\Users\\andrewjo\\Documents\\Some" +
                            "thing.accdb (Access 2007 - 2013 file format)");
                    #endregion
                }
                return this.mUIItemCustom3;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private WinCustom mUIItemCustom1;
        
        private WinCustom mUIItemCustom2;
        
        private UIItemWindow mUIItemWindow;
        
        private WinCustom mUIItemCustom3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "OKttbx";
            this.WindowTitles.Add("Microsoft Access Preview - Something : Database- C:\\Users\\andrewjo\\Documents\\Some" +
                    "thing.accdb (Access 2007 - 2013 file format)");
            #endregion
        }
        
        #region Properties
        public WinClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIItemClient.WindowTitles.Add("Microsoft Access Preview - Something : Database- C:\\Users\\andrewjo\\Documents\\Some" +
                            "thing.accdb (Access 2007 - 2013 file format)");
                    #endregion
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISaveAsWindow : WinWindow
    {
        
        public UISaveAsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Save As";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Save As");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Save As");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
}
